// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/currency/currency.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` //currency_code // DB
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` //currency_name // DB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyRequest) Reset() {
	*x = CreateCurrencyRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyRequest) ProtoMessage() {}

func (x *CreateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCurrencyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateCurrencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrenciesRequest) Reset() {
	*x = GetCurrenciesRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrenciesRequest) ProtoMessage() {}

func (x *GetCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*GetCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrenciesRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyResponse) Reset() {
	*x = CurrencyResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyResponse) ProtoMessage() {}

func (x *CurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyResponse.ProtoReflect.Descriptor instead.
func (*CurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{2}
}

func (x *CurrencyResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CurrencyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      []*CurrencyResponse    `protobuf:"bytes,1,rep,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesResponse) Reset() {
	*x = ListCurrenciesResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesResponse) ProtoMessage() {}

func (x *ListCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{3}
}

func (x *ListCurrenciesResponse) GetCurrency() []*CurrencyResponse {
	if x != nil {
		return x.Currency
	}
	return nil
}

type DeleteCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyResponse) Reset() {
	*x = DeleteCurrencyResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyResponse) ProtoMessage() {}

func (x *DeleteCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyResponse.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCurrencyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_currency_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{5}
}

var File_proto_currency_currency_proto protoreflect.FileDescriptor

const file_proto_currency_currency_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/currency/currency.proto\x12\bcurrency\"?\n" +
	"\x15CreateCurrencyRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"*\n" +
	"\x14GetCurrenciesRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\":\n" +
	"\x10CurrencyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"P\n" +
	"\x16ListCurrenciesResponse\x126\n" +
	"\bcurrency\x18\x01 \x03(\v2\x1a.currency.CurrencyResponseR\bcurrency\"2\n" +
	"\x16DeleteCurrencyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Empty2\xbd\x02\n" +
	"\x0fCurrencyService\x12M\n" +
	"\x0eCreateCurrency\x12\x1f.currency.CreateCurrencyRequest\x1a\x1a.currency.CurrencyResponse\x12K\n" +
	"\rGetCurrencies\x12\x1e.currency.GetCurrenciesRequest\x1a\x1a.currency.CurrencyResponse\x12F\n" +
	"\x11GetListCurrencies\x12\x0f.currency.Empty\x1a .currency.ListCurrenciesResponse\x12F\n" +
	"\x11DeleteAllCurrency\x12\x0f.currency.Empty\x1a .currency.DeleteCurrencyResponseB2Z0github.com/DmitryGoculyak/Protos-/proto/currencyb\x06proto3"

var (
	file_proto_currency_currency_proto_rawDescOnce sync.Once
	file_proto_currency_currency_proto_rawDescData []byte
)

func file_proto_currency_currency_proto_rawDescGZIP() []byte {
	file_proto_currency_currency_proto_rawDescOnce.Do(func() {
		file_proto_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_currency_currency_proto_rawDesc), len(file_proto_currency_currency_proto_rawDesc)))
	})
	return file_proto_currency_currency_proto_rawDescData
}

var file_proto_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_currency_currency_proto_goTypes = []any{
	(*CreateCurrencyRequest)(nil),  // 0: currency.CreateCurrencyRequest
	(*GetCurrenciesRequest)(nil),   // 1: currency.GetCurrenciesRequest
	(*CurrencyResponse)(nil),       // 2: currency.CurrencyResponse
	(*ListCurrenciesResponse)(nil), // 3: currency.ListCurrenciesResponse
	(*DeleteCurrencyResponse)(nil), // 4: currency.DeleteCurrencyResponse
	(*Empty)(nil),                  // 5: currency.Empty
}
var file_proto_currency_currency_proto_depIdxs = []int32{
	2, // 0: currency.ListCurrenciesResponse.currency:type_name -> currency.CurrencyResponse
	0, // 1: currency.CurrencyService.CreateCurrency:input_type -> currency.CreateCurrencyRequest
	1, // 2: currency.CurrencyService.GetCurrencies:input_type -> currency.GetCurrenciesRequest
	5, // 3: currency.CurrencyService.GetListCurrencies:input_type -> currency.Empty
	5, // 4: currency.CurrencyService.DeleteAllCurrency:input_type -> currency.Empty
	2, // 5: currency.CurrencyService.CreateCurrency:output_type -> currency.CurrencyResponse
	2, // 6: currency.CurrencyService.GetCurrencies:output_type -> currency.CurrencyResponse
	3, // 7: currency.CurrencyService.GetListCurrencies:output_type -> currency.ListCurrenciesResponse
	4, // 8: currency.CurrencyService.DeleteAllCurrency:output_type -> currency.DeleteCurrencyResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_currency_currency_proto_init() }
func file_proto_currency_currency_proto_init() {
	if File_proto_currency_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_currency_currency_proto_rawDesc), len(file_proto_currency_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_currency_proto_goTypes,
		DependencyIndexes: file_proto_currency_currency_proto_depIdxs,
		MessageInfos:      file_proto_currency_currency_proto_msgTypes,
	}.Build()
	File_proto_currency_currency_proto = out.File
	file_proto_currency_currency_proto_goTypes = nil
	file_proto_currency_currency_proto_depIdxs = nil
}
